export enum ConversationEventType {
    CONVERSATION_START = 'CONVERSATION_START',
    PATTERN_DRIFT_DETECTED = 'PATTERN_DRIFT_DETECTED',
    USER_FRUSTRATION_SPIKE = 'USER_FRUSTRATION_SPIKE',
    GOOD_CALIBRATION = 'GOOD_CALIBRATION',
    TRAUMA_TRIGGERED = 'TRAUMA_TRIGGERED',
    USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
}

export enum OrchestrationEventType {
    AGENT_SPAWNED = 'AGENT_SPAWNED',
    TASK_DELEGATED = 'TASK_DELEGATED',
    CONSENSUS_REACHED = 'CONSENSUS_REACHED',
    CONFLICT_DETECTED = 'CONFLICT_DETECTED',
    LEADER_ELECTED = 'LEADER_ELECTED',
}

export enum ReasoningEventType {
    TOT_BRANCH_EXPLORED = 'TOT_BRANCH_EXPLORED',
    CRITIC_OVERRIDE = 'CRITIC_OVERRIDE',
    VERIFIER_PASSED = 'VERIFIER_PASSED',
    HALLUCINATION_DETECTED = 'HALLUCINATION_DETECTED',
}
